# Introduction

This Marine Sensitivity (MS) project of [BOEM](https://boem.gov) seeks to assess the sensitivity of marine species to offshore energy development, whether oil & gas or wind. By combining the best available species distributions with known species sensitivities we can map out areas of the ocean that are most vulnerable to human activities. This information can be used to inform decisions about where to place energy infrastructure and/or implement mitigations to minimize impacts on the marine environment.

This is a process, not a product. Information is imperfect, especially given the large expanse of US waters. Distributions and abundance of species change, modified increasingly by climate change and human activities. Knowledge on species sensitivities continues to expand with more research. And finally the methods for both modeling and distributing all this information continue to improve. We aim to provide a transparent and reproducible process that can be regularly updated as new data and methods become available.

```{mermaid}
%%| label: fig-process
%%| fig-cap: "Flowchart of process for incorporating marine species sensitivities with distributions and generating a holistic vulnerability map."
%%| file: diagrams/process.mmd
%%| fig-width: 6
```

