sequenceDiagram
  autonumber
  Client      ->> ShinyServer: request Shiny map app with a raster layer
  ShinyServer ->> Client:      return JavaScript (JS) with URL specification for raster tiles
  loop for every tile in the current view (based on zoom level and bounding box)
    Client     ->> TiTiler:    request specific raster tile ({z}/{x}/{y})
    TiTiler    ->> FileServer: read metadata from COG file and request byte range for tile ({z}/{x}/{y})
    FileServer ->> TiTiler:    send byte range for tile
    TiTiler    ->> Client:     apply color ramp to tile and return PNG
  end
